name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --release

    - name: Run tests
      run: cargo test --verbose

    - name: Publish built binary to GitHub releases
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Force-update the Git tag to point to the current commit
        git tag -f prerelease
        git push -f origin prerelease

        # Create or overwrite the pre-release
        gh release create prerelease ./target/release/game-params \
          --prerelease \
          --title "Binary builds" \
          --generate-notes \
          --clobber

