name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: game-params
        path: target/release/game-params

    - uses: actions/checkout@v6
    - name: Download release artifact
      uses: actions/download-artifact@v5
      with:
        name: game-params
        path: ./target/release/game-params
    - name: Publish built binary to GitHub releases
    - run: |
      gh release create prerelease ./target/release/game-params --prerelease --title "Binary builds"
