name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build
      run: cargo build --release

    - name: Run tests
      run: cargo test --verbose

    - name: Test
      run: echo ${{ matrix.BUILD_TARGET }}

    - name: Publish built binary to GitHub releases
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TARGET_ARCH=$(rustc -Vv | grep host | cut -d ' ' -f 2)
        ARCHIVE_NAME="game-params-${TARGET_ARCH}.tar.gz"

        tar -czf "$ARCHIVE_NAME" -C target/release game-params

        # Force-update the Git tag to point to the current commit
        git tag -f prerelease
        git push -f origin prerelease

        gh release delete prerelease --yes || true

        # Create or overwrite the pre-release
        gh release create prerelease "./$ARCHIVE_NAME" \
          --prerelease \
          --title "Binary builds" \
          --generate-notes

